### ISSUE TITLE
[Feature Request] Preview Window of selected area

### ISSUE THREAD

**Issue by 0lm** [iCallH4x/OCR-PY#4]
Hello there

I actually stumbled over this very early, when it was still made for Pc Build Sim 2 only and tested this. If I remember right, the very early version of this script actually had a preview window of the coordinates. This kinda really helped to check, if you put the coordinates right or wrong. Is there a possibility to add this again?

If you dont want it to be a thing in the script, could you maybe make it selectable, if one wants to turn on the preview window or not, at the start of the script?

Thanks for your work on this script, regardless of your decision.

**Comment by iCallH4x** [comment]
Sure! I forgot to re-add that, but I definitely will.

**Comment by iCallH4x** [comment]
I added the image preview to the 'sniping' part so you can verify that the box is in the right area. I didn't add it to the normal OCR function as it shows in console and you would know pretty instantly if it's the right text or not.
